train:
  _target_: src.datasets.TextDataset
  name: "train"
  block_size: 20
  tokenizer:
    _target_: src.tokenizers.NaiveTokenizer
test:
  _target_: src.datasets.TextDataset
  name: "test"
  block_size: 20
  tokenizer:
    _target_: src.tokenizers.NaiveTokenizer
