train:
  _target_: src.datasets.ShakespeareDataset
  part: "train"
  max_seq_len: ${max_seq_len}
  val_ratio: 0.1
  transforms: ${instance_transforms.train}
val:
  _target_: src.datasets.ShakespeareDataset
  part: "val"
  max_seq_len: ${max_seq_len}
  val_ratio: 0.1
  transforms: ${instance_transforms.inference}
