train:
  data_object: # name of the tensor on which we apply transform
    _target_: torch.nn.Sequential # to apply several transforms sequentially
    _args_:
      - _target_: src.transforms.Normalize1D
        mean: 0.1307
        std: 0.3081
inference:
  data_object: # name of the tensor on which we apply transform
    _target_: torch.nn.Sequential # to apply several transforms sequentially
    _args_:
      - _target_: src.transforms.Normalize1D
        mean: 0.1307
        std: 0.3081
