_target_: src.model.GPT
decoder:
  _target_: src.model.TransformerDecoder
  d_model: 512
  vocab_size: 1
  num_layers: 6
  num_heads: 8
  seq_dropout: 0.1
  ffn_dropout: 0.1
  attn_dropout: 0.1
  use_trainable_pos_embeds: False
  max_seq_len: None
beam_width: 8
context_len: 512
max_new_tokens: 2048
