defaults:
  - _self_

model_overrides:
  beam_width: 32
  beam_temperature: 1.3
  use_prob_sampling: True

checkpoint: saved/tiny_stories/model_best.pth
tokenizer_vocab: saved/tiny_stories/tokenizer.json
text: "Ones upon a time"
device: auto
seed: null
